// Generated by Wrangler on Sat Apr 06 2024 14:39:57 GMT+1100 (Australian Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
